version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: postgres:10
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_dev

volumes:
  dbdata:
    driver: local
